#!/bin/bash
#only can have 1D arrays

#declaration
fav_nums=(3.14 2.718 0.57721 4.6692)

#print individual index
echo "Pi : ${fav_nums[0]}"

#append to array
fav_nums[4]=1.618

echo "GR : ${fav_nums[4]}"

#append multiples to array
fav_nums+=(1 7)

#for loop print every element
for i in ${fav_nums[*]}; do
	echo $i
done

#print out all indexes
for i in ${fav_nums[@]}; do
	echo $i
done

#length of array
echo "Array Length : ${#fav_nums[@]}"

#length of individual element
echo "Index 3 Length : ${#fav_nums[3]}"

#sort the array
sorted_nums=($(for i in "${fav_nums[@]}"; do
	echo $i;
done | sort ))

for i in ${sorted_nums[*]}; do
	echo $i
done

#delete an element
unset 'sorted_nums[1]'

#delete array
unset sorted_nums
